### ISSUE TITLE
Compatibility for 9.2

### ISSUE THREAD

**Issue by roshanroche** [InfotelGLPI/additionalalerts#3]
Hello,
thanks for the useful plugin. 
need compatible version for GLPI 9.2

**Comment by amma35** [comment]
see [2.0.0](https://github.com/InfotelGLPI/additionalalerts/releases/tag/2.0.0)

**Comment by roshanroche** [comment]
Dear @amma35 ,
Thanks for the update.

**Comment by roshanroche** [comment]
Dear @amma35 
i installed the plugin on Glpi 9.2 im getting the following errors when enabled unresolved tickets option.its not sending out notifications for unresolved tickets

![image](https://user-images.githubusercontent.com/22425503/36412201-a0dde7ee-1632-11e8-81f3-abf36b83d40b.png)
