### ISSUE TITLE
Question regarding ink level

### ISSUE THREAD

**Issue by roshanroche** [InfotelGLPI/additionalalerts#5]
Hello,
I have a question regarding the plugin. In ink level notification where do I set percentage of ink level threshold to trigger the notification. Example if I want notification when the ink level is 15% or less

**Comment by amma35** [comment]
Hi,
The alert works in connection with FusionInventory.
Fusioninventory changes the status of the printer then the alert checks the status of the printer.
To configure this parameter, this is done in the automatic action.

**Comment by roshanroche** [comment]
Hello @amma35 ,
Thanks for the reply. I have set up FI and SNMP is done properly. But I’m not finding a way to set up threshold for what percentage the notification is sent. In automatic action there  is a field saying parameter status but what I should put here.

**Comment by amma35** [comment]
Hi, 
To configure the automatic action, you must select the states that are affected by this alert : 
![cron](https://user-images.githubusercontent.com/15138371/42802972-cb8ba9b4-89a4-11e8-8334-ab5b95f6dfc4.png)

Then for the threshold, there is a tab in the cartridges : 
![cartridges](https://user-images.githubusercontent.com/15138371/42802977-cd8b2f78-89a4-11e8-9507-22c83433ff05.png)
