### ISSUE TITLE
Compatible for GLPI 9.5

### ISSUE THREAD

**Issue by AlexanderBBB** [InfotelGLPI/additionalalerts#8]
Good day,
thanks for the useful plugin.
I need compatible version for GLPI 9.5

Thanks,
Alexander

**Comment by Speedlover73** [comment]
No answer ???

**Comment by trevenag01** [comment]
Yeah stopped working since 9.5 compatibility isnt there yet, do you know when we might get the next release?

Thanks,
Greg

**Comment by trevenag01** [comment]
> Yeah stopped working since 9.5 compatibility isnt there yet, do you know when we might get the next release?
> 
> Thanks,
> Greg
Any update was really useful or an alternative?

**Comment by sandr502** [comment]
i changed  parameter in setup.php, and it work find
|| version_compare(GLPI_VERSION, '9.5', 'ge')) {       
to 
|| version_compare(GLPI_VERSION, '9.6', 'ge')) {

**Comment by tsmr** [comment]
released version
